USE SCHEMA Company;
CREATE TABLE Company.HR_Test_1
(
   HRID VARCHAR
  ,HR_NAME VARCHAR
  ,HR_LOCATION VARCHAR
)
as SELECT * FROM COMPANY.HR_TEST;

DROP TABLE COMPANY.HR_TEST;

CREATE TABLE COMPANY.HR_TEST_1
(
   ID VARCHAR
  ,NAME VARCHAR
  ,LOCATION VARCHAR
);